//
//  main.cpp
//  NewIll
//
//  Created by Christopher Culter on 1/22/12.
//  Copyright 2012 __MyCompanyName__. All rights reserved.
//

#include <fstream>
#include <iostream>
#include <iomanip>
#include <math.h>

#include "Comp.h"
#include "Svg.h"
#include "Settings.h"

#include "Integers.h"
#include "Fractions.h"
#include "BarChart.h"

using namespace std;

void drawLine(comp integerCenter, comp fractionCenter, comp offset, double integerScale, double fractionScale, int integerValue, int integerExponent);
void drawLineWithColor(comp integerCenter, comp fractionCenter, comp offset, double integerScale, double fractionScale, int integerValue, int integerExponent);


void drawLine(comp integerCenter, comp fractionCenter, comp offset, double integerScale, double fractionScale, int integerValue, int integerExponent)
{
    comp integer = getPoint(integerCenter, integerScale, integerValue, integerExponent);
    
    indent::space();
    cout << "<path fill=\"none\" stroke=\"gray\" d=\"";
    cout << "M" << integer.getre() << "," << integer.getim() << " ";
    
    integer += offset;
    cout << "L" << integer.getre() << "," << integer.getim() << " ";
    cout << "L" << fractionCenter.getre() << "," << fractionCenter.getim() << " ";
    cout << "\" />\n";
}

void drawLabel(comp integerCenter, double integerScale, int integerValue, string name, double dx, string styleClass) {
    comp integer = getPoint(integerCenter, integerScale, integerValue, g_maxExponentInteger);
    
    std::cout << "<text x=\"" << integer.getre() + dx << "\" y=\"" << integer.getim() << "\" class=\"" << styleClass << "\">";
    std::cout << name;
    std::cout << "</text>\n";
}

void drawLabelAtPoint(comp point, string name) {    
    std::cout << "<text x=\"" << point.getre() << "\" y=\"" << point.getim() << "\" class=\"integerLabel\">";
    std::cout << name;
    std::cout << "</text>\n";
}

void drawLineWithColor(comp integerCenter, comp fractionCenter, comp offset, double integerScale, double fractionScale, int integerValue, int integerExponent, string name)
{
    drawLine(integerCenter, fractionCenter, offset, integerScale, fractionScale, integerValue, integerExponent);
    
    comp integer = getPoint(integerCenter, integerScale, integerValue, integerExponent);
    comp dz = fractionCenter - integer;
    bool labelOnTop = dz.getim() < -abs(dz.getre() / 2);

    comp integerToFractionCenter = fractionCenter - integer;
    comp direction = integerToFractionCenter / integerToFractionCenter.norm();
    double lengthToPerimeter = integerToFractionCenter.norm() - fractionScale;
    double lengthToName = lengthToPerimeter * 0.55;
    comp nameCenter = integer + (direction * lengthToName);
    drawLabelAtPoint(nameCenter, name);

    drawPruferColored(fractionCenter, fractionScale, integerValue, g_maxExponentFraction, labelOnTop);
}

int main (int argc, const char * argv[])
{    
    ofstream outFile("LocalAutoGenerated.svg");
    cout.rdbuf(outFile.rdbuf());
    
    g_events = false;
    g_maxExponentInteger = 8;
    g_maxExponentFraction = 6;
    g_scale = 1.0 / (1.0 + 1.0 / (sin(pi / prime)));
    
    cout << setprecision(6);
    
    preamble(600, 600);
    {
        indent inSvg;
        
        if (g_events)
        {
            beginScript();
            insertScript();
            endScript();
        }
        
        beginDefs();
        {
            indent inDefs;
            
            beginStyle();
            styleIntegers();
            stylePrufer();
            styleBars();
            endStyle();
            
            definePrufer();
        }
        
        endDefs();
        
//        drawBars(comp(125, 150), 3);
      
        //drawIntegers(comp(200, 200), 180 * (1.0 - g_scale));
        //drawPrufer(comp(600, 200), 180);
        
        comp center(300, 300);
        double integerScale = 180 * (1.0 - g_scale);
        double fractionSize = 42;
        double fractionDistance = 244;
        
        //2
        /*
        drawLineWithColor(center, center + circ( 6.0/13.0) * 240, comp(0, 0), integerScale, 50,   1+4+16+64+256+1024,  10);
        drawLineWithColor(center, center + circ(-6.0/13.0) * 240, comp(0, 0), integerScale, 50, -(1+4+16+64+256+1024), 10);
        
        drawLineWithColor(center, center + circ( 5.0/13.0) * 240, comp(0, 0), integerScale, 50,   1+8+64+512,  10);
        drawLineWithColor(center, center + circ(-5.0/13.0) * 240, comp(0, 0), integerScale, 50, -(1+8+64+512), 10);
        
        drawLineWithColor(center, center + circ( 4.0/13.0) * 240, comp(0, 0), integerScale, 50,  1, 10);
        drawLineWithColor(center, center + circ(-4.0/13.0) * 240, comp(0, 0), integerScale, 50, -1, 10);
        
        drawLineWithColor(center, center + circ( 3.0/13.0) * 240, comp(60, 0), integerScale, 50, -3, 10);
        drawLineWithColor(center, center + circ(-3.0/13.0) * 240, comp(60, 0), integerScale, 50,  3, 10);
        
        drawLineWithColor(center, center + circ( 2.0/13.0) * 240, comp(0, 0), integerScale, 50,  2, 10);
        drawLineWithColor(center, center + circ(-2.0/13.0) * 240, comp(0, 0), integerScale, 50, -2, 10);
        
        drawLineWithColor(center, center + circ( 1.0/13.0) * 240, comp(0, 0), integerScale, 50,  4, 10);
        drawLineWithColor(center, center + circ(-1.0/13.0) * 240, comp(0, 0), integerScale, 50, -4, 10);
        
        drawLineWithColor(center, center + circ(0.0) * 240, comp(0, 0), integerScale, 50, 0, g_maxExponent);
        */
        
        //3
        
        drawIntegers(center, integerScale);

        drawLineWithColor(center, center + circ( 6.0/13.0) * fractionDistance, comp(0, 0), integerScale, fractionSize, -(powi(3, 10) - 1) / 4, 9, "1⁄4");
        drawLineWithColor(center, center + circ(-6.0/13.0) * fractionDistance, comp(0, 0), integerScale, fractionSize,  (powi(3, 10) - 1) / 4, 9, "−1⁄4");
        
        drawLineWithColor(center, center + circ( 5.0/13.0) * fractionDistance, comp(0, 0), integerScale, fractionSize,  (powi(3, 10) - 1) / 2, 9, "−1⁄2");
        drawLineWithColor(center, center + circ(-5.0/13.0) * fractionDistance, comp(0, 0), integerScale, fractionSize, -(powi(3, 10) - 1) / 2, 9, "1⁄2");
        
        drawLineWithColor(center, center + circ( 4.0/13.0) * fractionDistance, comp(0, 0), integerScale, fractionSize,  (powi(3, 10) - 1) / 8, 9, "−1⁄8");
        drawLineWithColor(center, center + circ(-4.0/13.0) * fractionDistance, comp(0, 0), integerScale, fractionSize, -(powi(3, 10) - 1) / 8, 9, "1⁄8");
        
        drawLineWithColor(center, center + circ( 3.0/13.0) * fractionDistance, comp(0, 0), integerScale, fractionSize,  1, 10, "1");
        drawLineWithColor(center, center + circ(-3.0/13.0) * fractionDistance, comp(0, 0), integerScale, fractionSize, -1, 10, "−1");
        
        drawLineWithColor(center, center + circ( 2.0/13.0) * fractionDistance, comp(0, 0), integerScale, fractionSize,  3, 10, "3");
        drawLineWithColor(center, center + circ(-2.0/13.0) * fractionDistance, comp(0, 0), integerScale, fractionSize, -3, 10, "−3");
        
        drawLineWithColor(center, center + circ( 1.0/13.0) * fractionDistance, comp(0, 0), integerScale, fractionSize,  9, 10, "9");
        drawLineWithColor(center, center + circ(-1.0/13.0) * fractionDistance, comp(0, 0), integerScale, fractionSize, -9, 10, "−9");
        
        drawLineWithColor(center, center + circ(0.0) * fractionDistance, comp(0, 0), integerScale, fractionSize, 0, 10, "0");
        
        drawLabel(center, integerScale, 2, "2", 3.0, "smallLabelRight");
        drawLabel(center, integerScale, -2, "−2", 3.0, "smallLabelRight");
        drawLabel(center, integerScale, 4, "4", 3.0, "smallLabelRight");
        drawLabel(center, integerScale, -4, "−4", 3.0, "smallLabelRight");
        drawLabel(center, integerScale, 6, "6", 3.0, "smallLabelRight");
        drawLabel(center, integerScale, -6, "−6", 3.0, "smallLabelRight");
        drawLabel(center, integerScale, 7, "7", 3.0, "smallLabelRight");
        drawLabel(center, integerScale, -7, "−7", 3.0, "smallLabelRight");
        drawLabel(center, integerScale, 8, "8", 3.0, "smallLabelRight");
        drawLabel(center, integerScale, -8, "−8", 3.0, "smallLabelRight");
        
        drawLabel(center, integerScale, -((powi(3, 10) - 1) / 2) * 3, "3⁄2", -3.0, "smallLabelLeft");
        drawLabel(center, integerScale, ((powi(3, 10) - 1) / 2) * 3, "−3⁄2", -3.0, "smallLabelLeft");
        drawLabel(center, integerScale, -((powi(3, 10) - 1) / 2) * 5, "5⁄2", -3.0, "smallLabelLeft");
        drawLabel(center, integerScale, ((powi(3, 10) - 1) / 2) * 5, "−5⁄2", -3.0, "smallLabelLeft");
        // drawLabel(center, integerScale, -((powi(3, 10) - 1) / 2) * 15, "15⁄2", -3.0, "smallLabelLeft");
        // drawLabel(center, integerScale, ((powi(3, 10) - 1) / 2) * 15, "−15⁄2", -3.0, "smallLabelLeft");
    }
    
	postamble();
}














